"""Write the Instruqt challenge directories from challenges/.

challenges/NN-slug/ is the source of truth: assignment.md is the prose, and
setup/check/solve/cleanup.sh are the lifecycle scripts. Instruqt wants each
challenge as a directory beside instruqt/track/track.yml, with scripts named
<verb>-<host>. This copies assignment.md and writes wrappers that run the
repo's own script from the sandbox's clone, so a fix to a check ships by
merging, with no track push.

`instruqt track push` adds `id:` lines to the challenge and its tabs; they are
carried over here so the platform keeps matching them across rebuilds.

    uv run python scripts/build_track.py
"""

import re
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CHALLENGES = ROOT / "challenges"
TRACK = ROOT / "instruqt" / "track"
HOST = "workstation"
VERBS = ("setup", "check", "solve", "cleanup")

WRAPPER = """#!/usr/bin/env bash
# Generated by scripts/build_track.py. The script itself is challenges/{challenge}/{verb}.sh,
# run from the sandbox's clone of the repo.
set -euo pipefail
# shellcheck disable=SC1091
source /etc/workshop/env
{pre}exec bash "$WORKDIR/challenges/{challenge}/{verb}.sh"
"""
# Challenge setup sees Instruqt's participant variables even if the sandbox setup didn't.
SETUP_PRE = '"$WORKDIR/instruqt/bin/write-env"\n'


def split_frontmatter(text: str) -> tuple[str, str]:
    _, front, body = text.split("---\n", 2)
    return front, body


def carry_ids(new_front: str, old_front: str) -> str:
    """Copy the challenge id and tab ids (matched by title) from a pushed copy."""
    ml = re.MULTILINE
    challenge_id = re.search(r"^id: (\S+)$", old_front, ml)
    tab_ids = {title: i for i, title in re.findall(r"^- id: (\S+)\n\s+title: (.+)$", old_front, ml)}
    if challenge_id:
        new_front = re.sub(r"^(slug: .+\n)", rf"\1id: {challenge_id[1]}\n", new_front, count=1, flags=ml)
    for title, tab_id in tab_ids.items():
        new_front = re.sub(rf"^- title: {re.escape(title)}$", f"- id: {tab_id}\n  title: {title}", new_front, flags=ml)
    return new_front


def build(challenge: Path) -> None:
    out = TRACK / challenge.name
    old = out / "assignment.md"
    old_front = split_frontmatter(old.read_text())[0] if old.exists() else ""
    if out.exists():
        shutil.rmtree(out)
    out.mkdir(parents=True)

    front, body = split_frontmatter((challenge / "assignment.md").read_text())
    (out / "assignment.md").write_text(f"---\n{carry_ids(front, old_front)}---\n{body}")

    for verb in VERBS:
        if not (challenge / f"{verb}.sh").exists():
            continue
        script = out / f"{verb}-{HOST}"
        pre = SETUP_PRE if verb == "setup" else ""
        script.write_text(WRAPPER.format(challenge=challenge.name, verb=verb, pre=pre))
        script.chmod(0o755)
    print(f"wrote {out.relative_to(ROOT)}")


def main() -> None:
    for challenge in sorted(p for p in CHALLENGES.iterdir() if (p / "assignment.md").exists()):
        build(challenge)


if __name__ == "__main__":
    main()
